name: Android Build

on:
  push:
    branches: [ "android" ]
  pull_request:
    branches: [ "android" ]

permissions:
  contents: write

jobs:
  build_android:
    name: Build Android APK
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
          
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          
      - name: Get Dependencies
        working-directory: jar_talk
        run: flutter pub get
        
      - name: Build APK
        working-directory: jar_talk
        run: flutter build apk --release
        
      - name: Release APK
        if: github.event_name == 'push'
        uses: softprops/action-gh-release@v1
        with:
          tag_name: android-latest
          files: jar_talk/build/app/outputs/flutter-apk/app-release.apk
          name: "Android Build ${{ github.sha }}"
          body: "Latest android build from commit ${{ github.sha }}"
          allow_updates: true
          prerelease: true
